In [1]:
import pandas as pd

In [2]:
sold0 = pd.read_csv("CRMLSSold202401.csv")
sold1 = pd.read_csv("CRMLSSold202402.csv")
sold2 = pd.read_csv("CRMLSSold202403.csv")
sold3 = pd.read_csv("CRMLSSold202404.csv")
sold4 = pd.read_csv("CRMLSSold202405_filled.csv")
sold5 = pd.read_csv("CRMLSSold202406_filled.csv")
sold6 = pd.read_csv("CRMLSSold202407_filled.csv")
sold7 = pd.read_csv("CRMLSSold202408.csv")
sold8 = pd.read_csv("CRMLSSold202409.csv")
sold9 = pd.read_csv("CRMLSSold202410.csv")
sold10 = pd.read_csv("CRMLSSold202411.csv")
sold11 = pd.read_csv("CRMLSSold202412.csv")
sold12 = pd.read_csv("CRMLSSold202501_filled.csv")
sold13 = pd.read_csv("CRMLSSold202502.csv")
sold14 = pd.read_csv("CRMLSSold202503.csv")
sold15 = pd.read_csv("CRMLSSold202504.csv")
sold16 = pd.read_csv("CRMLSSold202505.csv")
sold17 = pd.read_csv("CRMLSSold202506.csv")
sold18 = pd.read_csv("CRMLSSold202507.csv")
sold19 = pd.read_csv("CRMLSSold202508.csv")
sold20 = pd.read_csv("CRMLSSold202509.csv")
sold21 = pd.read_csv("CRMLSSold202510.csv")
sold22 = pd.read_csv("CRMLSSold202511.csv")
sold23 = pd.read_csv("CRMLSSold202512.csv")
sold24 = pd.read_csv("CRMLSSold202601.csv")
sold25 = pd.read_csv("CRMLSSold202602.csv")
sold26 = pd.read_csv("CRMLSSold202603.csv")
sold27 = pd.read_csv("CRMLSSold202604.csv")
sold28 = pd.read_csv("CRMLSSold202605.csv")

C:\Users\junki\AppData\Local\Temp\ipykernel_23056\1667112100.py:4: DtypeWarning: Columns (0: WaterfrontYN, 1: ElementarySchool, 2: BuilderName, 3: CoBuyerAgentFirstName, 4: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  sold3 = pd.read_csv("CRMLSSold202404.csv")
C:\Users\junki\AppData\Local\Temp\ipykernel_23056\1667112100.py:18: DtypeWarning: Columns (0: WaterfrontYN) have mixed types. Specify dtype option on import or set low_memory=False.
  sold17 = pd.read_csv("CRMLSSold202506.csv")
C:\Users\junki\AppData\Local\Temp\ipykernel_23056\1667112100.py:25: DtypeWarning: Columns (0: WaterfrontYN, 1: PostalCode) have mixed types. Specify dtype option on import or set low_memory=False.
  sold24 = pd.read_csv("CRMLSSold202601.csv")

In [3]:
print(sold0.shape)
print(sold1.shape)
print(sold2.shape)
print(sold3.shape)
print(sold4.shape)
print(sold5.shape)
print(sold6.shape)
print(sold7.shape)
print(sold8.shape)
print(sold9.shape)
print(sold10.shape)
print(sold11.shape)
print(sold12.shape)
print(sold13.shape)
print(sold14.shape)
print(sold15.shape)
print(sold16.shape)
print(sold17.shape)
print(sold18.shape)
print(sold19.shape)
print(sold20.shape)
print(sold21.shape)
print(sold22.shape)
print(sold23.shape)
print(sold24.shape)
print(sold25.shape)
print(sold26.shape)
print(sold27.shape)
print(sold28.shape)

(17976, 80)
(19925, 78)
(23276, 78)
(24640, 78)
(26487, 80)
(24328, 80)
(26240, 80)
(24558, 78)
(21267, 78)
(23274, 78)
(20279, 78)
(20241, 78)
(18738, 80)
(18702, 78)
(21445, 78)
(23262, 78)
(23154, 78)
(22883, 78)
(23646, 78)
(22972, 78)
(22443, 78)
(23233, 78)
(19088, 78)
(20538, 78)
(16487, 78)
(19010, 80)
(23372, 80)
(24261, 80)
(24191, 79)

In [4]:
sold = [sold0, sold1, sold2, sold3, sold4, sold5, sold6, sold7, sold8, sold9, sold10, sold11, sold12, sold13, sold14, sold15, sold16, sold17, sold18, sold19, sold20, sold21, sold22, sold23, sold24, sold25, sold26, sold27, sold28]

for i in range(len(sold)):
    for j in range(i+1,len(sold)):
        if i != j:
            diff_i_j = set(sold[i].columns) - set(sold[j].columns)
            diff_j_i = set(sold[j].columns) - set(sold[i].columns)  
                 
        if diff_i_j or diff_j_i:
            print(f"\nsold[{i}] vs sold[{j}]")
            print(f"Columns in sold[{i}] but not sold[{j}]:", diff_i_j)
            print(f"Columns in sold[{j}] but not sold[{i}]:", diff_j_i)

sold[0] vs sold[1]
Columns in sold[0] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}
Columns in sold[1] but not sold[0]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}

sold[0] vs sold[2]
Columns in sold[0] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}
Columns in sold[2] but not sold[0]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}

sold[0] vs sold[3]
Columns in sold[0] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}
Columns in sold[3] but not sold[0]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}

sold[0] vs sold[4]
Columns in sold[0] but not sold[4]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[4] but not sold[0]: {'lonfilled', 'latfilled'}

sold[0] vs sold[5]
Columns in sold[0] but not sold[5]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[5] but not sold[0]: {'lonfilled', 'latfilled'}

sold[0] vs sold[6]
Columns in sold[0] but not sold[6]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[6] but not sold[0]: {'lonfilled', 'latfilled'}

sold[0] vs sold[7]
Columns in sold[0] but not sold[7]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[7] but not sold[0]: set()

sold[0] vs sold[8]
Columns in sold[0] but not sold[8]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[8] but not sold[0]: set()

sold[0] vs sold[9]
Columns in sold[0] but not sold[9]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[9] but not sold[0]: set()

sold[0] vs sold[10]
Columns in sold[0] but not sold[10]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[10] but not sold[0]: set()

sold[0] vs sold[11]
Columns in sold[0] but not sold[11]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[11] but not sold[0]: set()

sold[0] vs sold[12]
Columns in sold[0] but not sold[12]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[12] but not sold[0]: {'lonfilled', 'latfilled'}

sold[0] vs sold[13]
Columns in sold[0] but not sold[13]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[13] but not sold[0]: set()

sold[0] vs sold[14]
Columns in sold[0] but not sold[14]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[14] but not sold[0]: set()

sold[0] vs sold[15]
Columns in sold[0] but not sold[15]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[15] but not sold[0]: set()

sold[0] vs sold[16]
Columns in sold[0] but not sold[16]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[16] but not sold[0]: set()

sold[0] vs sold[17]
Columns in sold[0] but not sold[17]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[17] but not sold[0]: set()

sold[0] vs sold[18]
Columns in sold[0] but not sold[18]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[18] but not sold[0]: set()

sold[0] vs sold[19]
Columns in sold[0] but not sold[19]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[19] but not sold[0]: set()

sold[0] vs sold[20]
Columns in sold[0] but not sold[20]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[20] but not sold[0]: set()

sold[0] vs sold[21]
Columns in sold[0] but not sold[21]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[21] but not sold[0]: set()

sold[0] vs sold[22]
Columns in sold[0] but not sold[22]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[22] but not sold[0]: set()

sold[0] vs sold[23]
Columns in sold[0] but not sold[23]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[23] but not sold[0]: set()

sold[0] vs sold[24]
Columns in sold[0] but not sold[24]: {'OriginatingSystemName', 'OriginatingSystemSubName'}
Columns in sold[24] but not sold[0]: set()

sold[0] vs sold[28]
Columns in sold[0] but not sold[28]: {'ListAgentEmail'}
Columns in sold[28] but not sold[0]: set()

sold[1] vs sold[4]
Columns in sold[1] but not sold[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[4] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[1] vs sold[5]
Columns in sold[1] but not sold[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[5] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[1] vs sold[6]
Columns in sold[1] but not sold[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[6] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[1] vs sold[7]
Columns in sold[1] but not sold[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[7] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[8]
Columns in sold[1] but not sold[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[8] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[9]
Columns in sold[1] but not sold[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[9] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[10]
Columns in sold[1] but not sold[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[10] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[11]
Columns in sold[1] but not sold[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[11] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[12]
Columns in sold[1] but not sold[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[12] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[1] vs sold[13]
Columns in sold[1] but not sold[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[13] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[14]
Columns in sold[1] but not sold[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[14] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[15]
Columns in sold[1] but not sold[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[15] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[16]
Columns in sold[1] but not sold[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[16] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[17]
Columns in sold[1] but not sold[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[17] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[18]
Columns in sold[1] but not sold[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[18] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[19]
Columns in sold[1] but not sold[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[19] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[20]
Columns in sold[1] but not sold[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[20] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[21]
Columns in sold[1] but not sold[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[21] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[22]
Columns in sold[1] but not sold[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[22] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[23]
Columns in sold[1] but not sold[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[23] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[24]
Columns in sold[1] but not sold[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[24] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[1] vs sold[25]
Columns in sold[1] but not sold[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[25] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[1] vs sold[26]
Columns in sold[1] but not sold[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[26] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[1] vs sold[27]
Columns in sold[1] but not sold[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[27] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[1] vs sold[28]
Columns in sold[1] but not sold[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in sold[28] but not sold[1]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[2] vs sold[4]
Columns in sold[2] but not sold[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[4] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[2] vs sold[5]
Columns in sold[2] but not sold[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[5] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[2] vs sold[6]
Columns in sold[2] but not sold[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[6] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[2] vs sold[7]
Columns in sold[2] but not sold[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[7] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[8]
Columns in sold[2] but not sold[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[8] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[9]
Columns in sold[2] but not sold[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[9] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[10]
Columns in sold[2] but not sold[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[10] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[11]
Columns in sold[2] but not sold[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[11] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[12]
Columns in sold[2] but not sold[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[12] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[2] vs sold[13]
Columns in sold[2] but not sold[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[13] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[14]
Columns in sold[2] but not sold[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[14] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[15]
Columns in sold[2] but not sold[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[15] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[16]
Columns in sold[2] but not sold[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[16] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[17]
Columns in sold[2] but not sold[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[17] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[18]
Columns in sold[2] but not sold[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[18] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[19]
Columns in sold[2] but not sold[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[19] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[20]
Columns in sold[2] but not sold[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[20] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[21]
Columns in sold[2] but not sold[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[21] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[22]
Columns in sold[2] but not sold[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[22] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[23]
Columns in sold[2] but not sold[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[23] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[24]
Columns in sold[2] but not sold[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[24] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[2] vs sold[25]
Columns in sold[2] but not sold[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[25] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[2] vs sold[26]
Columns in sold[2] but not sold[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[26] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[2] vs sold[27]
Columns in sold[2] but not sold[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[27] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[2] vs sold[28]
Columns in sold[2] but not sold[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in sold[28] but not sold[2]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[3] vs sold[4]
Columns in sold[3] but not sold[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[4] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[3] vs sold[5]
Columns in sold[3] but not sold[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[5] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[3] vs sold[6]
Columns in sold[3] but not sold[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[6] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[3] vs sold[7]
Columns in sold[3] but not sold[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[7] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[8]
Columns in sold[3] but not sold[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[8] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[9]
Columns in sold[3] but not sold[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[9] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[10]
Columns in sold[3] but not sold[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[10] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[11]
Columns in sold[3] but not sold[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[11] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[12]
Columns in sold[3] but not sold[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[12] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'latfilled', 'lonfilled'}

sold[3] vs sold[13]
Columns in sold[3] but not sold[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[13] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[14]
Columns in sold[3] but not sold[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[14] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[15]
Columns in sold[3] but not sold[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[15] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[16]
Columns in sold[3] but not sold[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[16] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[17]
Columns in sold[3] but not sold[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[17] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[18]
Columns in sold[3] but not sold[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[18] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[19]
Columns in sold[3] but not sold[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[19] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[20]
Columns in sold[3] but not sold[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[20] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[21]
Columns in sold[3] but not sold[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[21] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[22]
Columns in sold[3] but not sold[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[22] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[23]
Columns in sold[3] but not sold[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[23] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[24]
Columns in sold[3] but not sold[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[24] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR'}

sold[3] vs sold[25]
Columns in sold[3] but not sold[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[25] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[3] vs sold[26]
Columns in sold[3] but not sold[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[26] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[3] vs sold[27]
Columns in sold[3] but not sold[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in sold[27] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[3] vs sold[28]
Columns in sold[3] but not sold[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in sold[28] but not sold[3]: {'ListAgentAOR', 'BuyerAgentAOR', 'OriginatingSystemSubName', 'OriginatingSystemName'}

sold[4] vs sold[7]
Columns in sold[4] but not sold[7]: {'lonfilled', 'latfilled'}
Columns in sold[7] but not sold[4]: set()

sold[4] vs sold[8]
Columns in sold[4] but not sold[8]: {'lonfilled', 'latfilled'}
Columns in sold[8] but not sold[4]: set()

sold[4] vs sold[9]
Columns in sold[4] but not sold[9]: {'lonfilled', 'latfilled'}
Columns in sold[9] but not sold[4]: set()

sold[4] vs sold[10]
Columns in sold[4] but not sold[10]: {'lonfilled', 'latfilled'}
Columns in sold[10] but not sold[4]: set()

sold[4] vs sold[11]
Columns in sold[4] but not sold[11]: {'lonfilled', 'latfilled'}
Columns in sold[11] but not sold[4]: set()

sold[4] vs sold[13]
Columns in sold[4] but not sold[13]: {'lonfilled', 'latfilled'}
Columns in sold[13] but not sold[4]: set()

sold[4] vs sold[14]

In [6]:
df_sold = pd.concat(sold)

row_df_sold = df_sold.shape[0]

print(df_sold.shape)

df_sold.head()

(639916, 84)

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [7]:
df_sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='str')

The columns that are useful considering domain perspective of analyzing housing market following

In [8]:
keep_cols = [
    # IDs
    "ListingKey",
    "ListingKeyNumeric",
    "ListingId",

    # Dates
    "CloseDate",
    "ListingContractDate",
    "PurchaseContractDate",
    "ContractStatusChangeDate",

    # Price fields
    "ClosePrice",
    "ListPrice",
    "OriginalListPrice",

    # Property characteristics
    "PropertyType",
    "PropertySubType",
    "LivingArea",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "YearBuilt",
    "DaysOnMarket",
    "LotSizeSquareFeet",

    # Location
    "Latitude",
    "Longitude",
    "UnparsedAddress",
    "City",
    "CountyOrParish",
    "PostalCode",
    "StateOrProvince",
    "MLSAreaMajor",
    
    # School
    "ElementarySchool",
    "ElementarySchoolDistrict",
    "MiddleOrJuniorSchool",
    "MiddleOrJuniorSchoolDistrict",
    "HighSchool",
    "HighSchoolDistrict",

    # Agent / office competitive analysis
    "ListAgentFirstName",
    "ListAgentLastName",
    "ListAgentFullName",
    "ListOfficeName",
    "BuyerAgentFirstName",
    "BuyerAgentLastName",
    "BuyerOfficeName",

    # Useful property features
    "GarageSpaces",
    "ParkingTotal",
    "FireplacesTotal",
    "FireplaceYN",
    "PoolPrivateYN",
    "WaterfrontYN",
    "ViewYN",
    "AttachedGarageYN",
    "NewConstructionYN",
    "Levels",
    "Stories",
    "TaxAnnualAmount",
    "TaxYear",
    "Flooring",
    "BasementYN",

    # Status
    "MlsStatus",
    "BusinessType",

    #Additional information property builder and neighborhood, or community
    "BuilderName",
    "SubdivisionName"    
]

In [9]:
df_sold = df_sold.drop(
    columns=[
        # which data system is from
        'OriginatingSystemSubName', 
        'OriginatingSystemName', 


        # Agent extra information as redundent.
        # Already included agent and office names
        "BuyerAgentAOR",
        "ListAgentAOR",
        "BuyerOfficeAOR",
        "AssociationFeeFrequency",
        "AssociationFee",

        # personal contact
        "ListAgentEmail",

        # Redundent information of property features
        "LotSizeAcres",
        "LotSizeDimensions",
        "LotSizeArea",
        "BuildingAreaTotal",
        "AboveGradeFinishedArea",
        "BelowGradeFinishedArea",
        "MainLevelBedrooms",
        "lonfilled",
        "latfilled",
        "StreetNumberNumeric",
        "CoveredSpaces"
        ]
    )

df_sold.shape

(639916, 65)

In [10]:
# check the property type 
print("List of property types:")
print(df_sold["PropertyType"].unique())
print()
print("List of property types of residential:")
print(df_sold[df_sold["PropertyType"]=="Residential"]["PropertySubType"].unique())

List of property types:
<StringArray>
[        'Residential',     'CommercialLease',                'Land',
    'ResidentialLease',  'ManufacturedInPark',   'ResidentialIncome',
      'CommercialSale', 'BusinessOpportunity']
Length: 8, dtype: str

List of property types of residential:
<StringArray>
[          'Condominium', 'SingleFamilyResidence',                'Duplex',
             'Townhouse',    'ManufacturedOnLand',             'Timeshare',
                     nan,            'MobileHome',               'Triplex',
      'StockCooperative',              'BoatSlip',              'MixedUse',
                 'Cabin',                  'Farm',      'ManufacturedHome',
            'Quadruplex',                  'Loft',            'OwnYourOwn',
         'DeededParking',           'CoOwnership',                'Studio']
Length: 21, dtype: str

Not all residential properties behave the same way in market. The	PropertyType	
and	PropertySubType	fields	in	the	MLS	distinguish	between	different	structures,	and	mixing	them	
in	an	analysis	without	filtering	can	produce	misleading	results.

Our target is residential properties that we must filter it from **PropertyType**.

In [11]:
df_sold = df_sold[df_sold["PropertyType"] == "Residential"]

print("List of property types:")
print(df_sold["PropertyType"].unique())

List of property types:
<StringArray>
['Residential']
Length: 1, dtype: str

In [12]:
print(df_sold[df_sold.duplicated(keep=False)])
print("Total duplicate rows:", df_sold["ListingKey"].duplicated().sum())

      Flooring ViewYN WaterfrontYN BasementYN PoolPrivateYN  \
1909       NaN  False          NaN        NaN         False
1910       NaN  False          NaN        NaN         False
4737       NaN  False          NaN        NaN         False
4738       NaN  False          NaN        NaN         False
8234      Tile  False          NaN        NaN         False
...        ...    ...          ...        ...           ...
2913       NaN  False          NaN        NaN         False
15451      NaN  False          NaN        NaN         False
15452      NaN  False          NaN        NaN         False
17464      NaN  False          NaN        NaN         False
17465      NaN  False          NaN        NaN         False

       OriginalListPrice  ListingKey   CloseDate  ClosePrice  \
1909           1299000.0  1079063603  2024-08-16   1269000.0
1910           1299000.0  1079063603  2024-08-16   1269000.0
4737           2000000.0  1077699506  2024-08-08   2000000.0
4738           2000000.0  1077699506  2024-08-08   2000000.0
8234           1195000.0  1077313817  2024-08-12   1224000.0
...                  ...         ...         ...         ...
2913           1099900.0  1119947269  2025-08-26   1100000.0
15451          3250000.0  1114799272  2025-08-08   2500000.0
15452          3250000.0  1114799272  2025-08-08   2500000.0
17464          1795000.0  1114185301  2025-08-29   1607300.0
17465          1795000.0  1114185301  2025-08-29   1607300.0

      ListAgentFirstName  ...  HighSchool   Levels  NewConstructionYN  \
1909                 Hui  ...         NaN      One               True
1910                 Hui  ...         NaN      One               True
4737            Michelle  ...         NaN  One,Two               True
4738            Michelle  ...         NaN  One,Two               True
8234              Kenzie  ...         NaN      One              False
...                  ...  ...         ...      ...                ...
2913                Gary  ...         NaN      One              False
15451               Sean  ...  Huntington      One              False
15452               Sean  ...  Huntington      One              False
17464              Kevin  ...         NaN      One              False
17465              Kevin  ...         NaN      One              False

      GarageSpaces           HighSchoolDistrict  PostalCode  \
1909           0.0           Los Nietos Unified       90606
1910           0.0           Los Nietos Unified       90606
4737           0.0           Bellflower Unified       90712
4738           0.0           Bellflower Unified       90712
8234           3.0             Pasadena Unified       91107
...            ...                          ...         ...
2913           0.0                          NaN       92113
15451          4.0  Huntington Beach Union High       92648
15452          4.0  Huntington Beach Union High       92648
17464          2.0                          NaN       92116
17465          2.0                          NaN       92116

       LotSizeSquareFeet  MiddleOrJuniorSchoolDistrict  \
1909              6380.0                           NaN
1910              6380.0                           NaN
4737              5376.0                           NaN
4738              5376.0                           NaN
8234              8575.0                           NaN
...                  ...                           ...
2913                 NaN                           NaN
15451             5663.0                           NaN
15452             5663.0                           NaN
17464                NaN                           NaN
17465                NaN                           NaN

      BuyerAgencyCompensationType BuyerAgencyCompensation
1909                          NaN                     NaN
1910                          NaN                     NaN
4737                          NaN                     NaN
4738                          NaN                     NaN
8234                          NaN                     NaN
...                           ...                     ...
2913                          NaN                     NaN
15451                         NaN                     NaN
15452                         NaN                     NaN
17464                         NaN                     NaN
17465                         NaN                     NaN

[96 rows x 65 columns]
Total duplicate rows: 370

There are extra duplicate properties of 594 in sold dataset. We will drop those duplicates and keep the lastest properties considering the date time order.

In [13]:
temp_close_date = pd.to_datetime(df_sold["CloseDate"], errors="coerce")
bad_dates = df_sold[
    df_sold["CloseDate"].notna() & temp_close_date.isna()
]

print(bad_dates[["ListingKey", "CloseDate"]])
print("Number of unreadable CloseDate values:", bad_dates.shape[0])

Empty DataFrame
Columns: [ListingKey, CloseDate]
Index: []
Number of unreadable CloseDate values: 0

In [14]:
before_properties = df_sold.shape[0]

df_sold["CloseDate"] = pd.to_datetime(df_sold["CloseDate"], errors = "coerce")

df_sold = (
    df_sold
    .sort_values("CloseDate")
    .drop_duplicates(subset = ["ListingKey"], keep="last")
    .reset_index(drop=True)
)
print("Number of dropped duplicate properties:", before_properties - df_sold.shape[0])
print("Remaining duplicated ListingKeys:", df_sold["ListingKey"].duplicated().sum())

Number of dropped duplicate properties: 370
Remaining duplicated ListingKeys: 0

In [15]:
listing0 = pd.read_csv("CRMLSListing202401.csv")
listing1 = pd.read_csv("CRMLSListing202402.csv")
listing2 = pd.read_csv("CRMLSListing202403.csv")
listing3 = pd.read_csv("CRMLSListing202404.csv")
listing4 = pd.read_csv("CRMLSListing202405.csv")
listing5 = pd.read_csv("CRMLSListing202406.csv")
listing6 = pd.read_csv("CRMLSListing202407.csv")
listing7 = pd.read_csv("CRMLSListing202408.csv")
listing8 = pd.read_csv("CRMLSListing202409.csv")
listing9 = pd.read_csv("CRMLSListing202410.csv")
listing10 = pd.read_csv("CRMLSListing202411.csv")
listing11 = pd.read_csv("CRMLSListing202412.csv")
listing12 = pd.read_csv("CRMLSListing202501.csv")
listing13 = pd.read_csv("CRMLSListing202502.csv")
listing14 = pd.read_csv("CRMLSListing202503.csv")
listing15 = pd.read_csv("CRMLSListing202504.csv")
listing16 = pd.read_csv("CRMLSListing202505.csv")
listing17 = pd.read_csv("CRMLSListing202506.csv")
listing18 = pd.read_csv("CRMLSListing202507.csv")
listing19 = pd.read_csv("CRMLSListing202508.csv")
listing20 = pd.read_csv("CRMLSListing202509.csv")
listing21 = pd.read_csv("CRMLSListing202510.csv")
listing22 = pd.read_csv("CRMLSListing202511.csv")
listing23 = pd.read_csv("CRMLSListing202512.csv")
listing24 = pd.read_csv("CRMLSListing202601.csv")
listing25 = pd.read_csv("CRMLSListing202602.csv")
listing26 = pd.read_csv("CRMLSListing202603.csv")
listing27 = pd.read_csv("CRMLSListing202604.csv")
listing28 = pd.read_csv("CRMLSListing202605.csv")

C:\Users\junki\AppData\Local\Temp\ipykernel_23056\4050626818.py:26: DtypeWarning: Columns (0: ElementarySchool, 1: BusinessType, 2: MiddleOrJuniorSchool, 3: HighSchool) have mixed types. Specify dtype option on import or set low_memory=False.
  listing25 = pd.read_csv("CRMLSListing202602.csv")

In [16]:
print(listing0.shape)
print(listing1.shape)
print(listing2.shape)
print(listing3.shape)
print(listing4.shape)
print(listing5.shape)
print(listing6.shape)
print(listing7.shape)
print(listing8.shape)
print(listing9.shape)
print(listing10.shape)
print(listing11.shape)
print(listing12.shape)
print(listing13.shape)
print(listing14.shape)
print(listing15.shape)
print(listing16.shape)
print(listing17.shape)
print(listing18.shape)
print(listing19.shape)
print(listing20.shape)
print(listing21.shape)
print(listing22.shape)
print(listing23.shape)
print(listing24.shape)
print(listing25.shape)
print(listing26.shape)
print(listing27.shape)
print(listing28.shape)

(27454, 84)
(27447, 84)
(32282, 84)
(36503, 84)
(38796, 82)
(35893, 82)
(36340, 82)
(35305, 82)
(34625, 82)
(34730, 82)
(25128, 82)
(19417, 82)
(37469, 82)
(33983, 82)
(38492, 82)
(40187, 82)
(40271, 82)
(26399, 82)
(27345, 82)
(25210, 82)
(26923, 82)
(27586, 82)
(20677, 82)
(18773, 82)
(2606, 82)
(32884, 82)
(39153, 82)
(39020, 82)
(36201, 81)

In [17]:
listings = [listing0, listing1, listing2, listing3, listing4, listing5, listing6,listing7, listing8, listing9, listing10, listing11, listing12,listing13, listing14, listing15, listing16, listing17, listing18,
    listing19, listing20, listing21, listing22, listing23, listing24,listing25, listing26, listing27, listing28
]

for i in range(len(listings)):
    for j in range(i+1,len(listings)):
        if i != j:
            diff_i_j = set(listings[i].columns) - set(listings[j].columns)
            diff_j_i = set(listings[j].columns) - set(listings[i].columns)  
                 
        if diff_i_j or diff_j_i:
            print(f"\nlistings[{i}] vs listings[{j}]")
            print(f"Columns in listings[{i}] but not listings[{j}]:", diff_i_j)
            print(f"Columns in listings[{j}] but not listings[{i}]:", diff_j_i)

listings[0] vs listings[4]
Columns in listings[0] but not listings[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[4] but not listings[0]: set()

listings[0] vs listings[5]
Columns in listings[0] but not listings[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[5] but not listings[0]: set()

listings[0] vs listings[6]
Columns in listings[0] but not listings[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[6] but not listings[0]: set()

listings[0] vs listings[7]
Columns in listings[0] but not listings[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[7] but not listings[0]: set()

listings[0] vs listings[8]
Columns in listings[0] but not listings[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[8] but not listings[0]: set()

listings[0] vs listings[9]
Columns in listings[0] but not listings[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[9] but not listings[0]: set()

listings[0] vs listings[10]
Columns in listings[0] but not listings[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[10] but not listings[0]: set()

listings[0] vs listings[11]
Columns in listings[0] but not listings[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[11] but not listings[0]: set()

listings[0] vs listings[12]
Columns in listings[0] but not listings[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[12] but not listings[0]: set()

listings[0] vs listings[13]
Columns in listings[0] but not listings[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[13] but not listings[0]: set()

listings[0] vs listings[14]
Columns in listings[0] but not listings[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[14] but not listings[0]: set()

listings[0] vs listings[15]
Columns in listings[0] but not listings[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[15] but not listings[0]: set()

listings[0] vs listings[16]
Columns in listings[0] but not listings[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[16] but not listings[0]: set()

listings[0] vs listings[17]
Columns in listings[0] but not listings[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[17] but not listings[0]: set()

listings[0] vs listings[18]
Columns in listings[0] but not listings[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[18] but not listings[0]: set()

listings[0] vs listings[19]
Columns in listings[0] but not listings[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[19] but not listings[0]: set()

listings[0] vs listings[20]
Columns in listings[0] but not listings[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[20] but not listings[0]: set()

listings[0] vs listings[21]
Columns in listings[0] but not listings[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[21] but not listings[0]: set()

listings[0] vs listings[22]
Columns in listings[0] but not listings[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[22] but not listings[0]: set()

listings[0] vs listings[23]
Columns in listings[0] but not listings[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[23] but not listings[0]: set()

listings[0] vs listings[24]
Columns in listings[0] but not listings[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[24] but not listings[0]: set()

listings[0] vs listings[25]
Columns in listings[0] but not listings[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[25] but not listings[0]: set()

listings[0] vs listings[26]
Columns in listings[0] but not listings[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[26] but not listings[0]: set()

listings[0] vs listings[27]
Columns in listings[0] but not listings[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[27] but not listings[0]: set()

listings[0] vs listings[28]
Columns in listings[0] but not listings[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in listings[28] but not listings[0]: set()

listings[1] vs listings[4]
Columns in listings[1] but not listings[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[4] but not listings[1]: set()

listings[1] vs listings[5]
Columns in listings[1] but not listings[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[5] but not listings[1]: set()

listings[1] vs listings[6]
Columns in listings[1] but not listings[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[6] but not listings[1]: set()

listings[1] vs listings[7]
Columns in listings[1] but not listings[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[7] but not listings[1]: set()

listings[1] vs listings[8]
Columns in listings[1] but not listings[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[8] but not listings[1]: set()

listings[1] vs listings[9]
Columns in listings[1] but not listings[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[9] but not listings[1]: set()

listings[1] vs listings[10]
Columns in listings[1] but not listings[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[10] but not listings[1]: set()

listings[1] vs listings[11]
Columns in listings[1] but not listings[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[11] but not listings[1]: set()

listings[1] vs listings[12]
Columns in listings[1] but not listings[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[12] but not listings[1]: set()

listings[1] vs listings[13]
Columns in listings[1] but not listings[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[13] but not listings[1]: set()

listings[1] vs listings[14]
Columns in listings[1] but not listings[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[14] but not listings[1]: set()

listings[1] vs listings[15]
Columns in listings[1] but not listings[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[15] but not listings[1]: set()

listings[1] vs listings[16]
Columns in listings[1] but not listings[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[16] but not listings[1]: set()

listings[1] vs listings[17]
Columns in listings[1] but not listings[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[17] but not listings[1]: set()

listings[1] vs listings[18]
Columns in listings[1] but not listings[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[18] but not listings[1]: set()

listings[1] vs listings[19]
Columns in listings[1] but not listings[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[19] but not listings[1]: set()

listings[1] vs listings[20]
Columns in listings[1] but not listings[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[20] but not listings[1]: set()

listings[1] vs listings[21]
Columns in listings[1] but not listings[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[21] but not listings[1]: set()

listings[1] vs listings[22]
Columns in listings[1] but not listings[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[22] but not listings[1]: set()

listings[1] vs listings[23]
Columns in listings[1] but not listings[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[23] but not listings[1]: set()

listings[1] vs listings[24]
Columns in listings[1] but not listings[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[24] but not listings[1]: set()

listings[1] vs listings[25]
Columns in listings[1] but not listings[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[25] but not listings[1]: set()

listings[1] vs listings[26]
Columns in listings[1] but not listings[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[26] but not listings[1]: set()

listings[1] vs listings[27]
Columns in listings[1] but not listings[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[27] but not listings[1]: set()

listings[1] vs listings[28]
Columns in listings[1] but not listings[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in listings[28] but not listings[1]: set()

listings[2] vs listings[4]
Columns in listings[2] but not listings[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[4] but not listings[2]: set()

listings[2] vs listings[5]
Columns in listings[2] but not listings[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[5] but not listings[2]: set()

listings[2] vs listings[6]
Columns in listings[2] but not listings[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[6] but not listings[2]: set()

listings[2] vs listings[7]
Columns in listings[2] but not listings[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[7] but not listings[2]: set()

listings[2] vs listings[8]
Columns in listings[2] but not listings[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[8] but not listings[2]: set()

listings[2] vs listings[9]
Columns in listings[2] but not listings[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[9] but not listings[2]: set()

listings[2] vs listings[10]
Columns in listings[2] but not listings[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[10] but not listings[2]: set()

listings[2] vs listings[11]
Columns in listings[2] but not listings[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[11] but not listings[2]: set()

listings[2] vs listings[12]
Columns in listings[2] but not listings[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[12] but not listings[2]: set()

listings[2] vs listings[13]
Columns in listings[2] but not listings[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[13] but not listings[2]: set()

listings[2] vs listings[14]
Columns in listings[2] but not listings[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[14] but not listings[2]: set()

listings[2] vs listings[15]
Columns in listings[2] but not listings[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[15] but not listings[2]: set()

listings[2] vs listings[16]
Columns in listings[2] but not listings[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[16] but not listings[2]: set()

listings[2] vs listings[17]
Columns in listings[2] but not listings[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[17] but not listings[2]: set()

listings[2] vs listings[18]
Columns in listings[2] but not listings[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[18] but not listings[2]: set()

listings[2] vs listings[19]
Columns in listings[2] but not listings[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[19] but not listings[2]: set()

listings[2] vs listings[20]
Columns in listings[2] but not listings[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[20] but not listings[2]: set()

listings[2] vs listings[21]
Columns in listings[2] but not listings[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[21] but not listings[2]: set()

listings[2] vs listings[22]
Columns in listings[2] but not listings[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[22] but not listings[2]: set()

listings[2] vs listings[23]
Columns in listings[2] but not listings[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[23] but not listings[2]: set()

listings[2] vs listings[24]
Columns in listings[2] but not listings[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[24] but not listings[2]: set()

listings[2] vs listings[25]
Columns in listings[2] but not listings[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[25] but not listings[2]: set()

listings[2] vs listings[26]
Columns in listings[2] but not listings[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[26] but not listings[2]: set()

listings[2] vs listings[27]
Columns in listings[2] but not listings[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[27] but not listings[2]: set()

listings[2] vs listings[28]
Columns in listings[2] but not listings[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in listings[28] but not listings[2]: set()

listings[3] vs listings[4]
Columns in listings[3] but not listings[4]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[4] but not listings[3]: set()

listings[3] vs listings[5]
Columns in listings[3] but not listings[5]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[5] but not listings[3]: set()

listings[3] vs listings[6]
Columns in listings[3] but not listings[6]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[6] but not listings[3]: set()

listings[3] vs listings[7]
Columns in listings[3] but not listings[7]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[7] but not listings[3]: set()

listings[3] vs listings[8]
Columns in listings[3] but not listings[8]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[8] but not listings[3]: set()

listings[3] vs listings[9]
Columns in listings[3] but not listings[9]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[9] but not listings[3]: set()

listings[3] vs listings[10]
Columns in listings[3] but not listings[10]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[10] but not listings[3]: set()

listings[3] vs listings[11]
Columns in listings[3] but not listings[11]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[11] but not listings[3]: set()

listings[3] vs listings[12]
Columns in listings[3] but not listings[12]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[12] but not listings[3]: set()

listings[3] vs listings[13]
Columns in listings[3] but not listings[13]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[13] but not listings[3]: set()

listings[3] vs listings[14]
Columns in listings[3] but not listings[14]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[14] but not listings[3]: set()

listings[3] vs listings[15]
Columns in listings[3] but not listings[15]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[15] but not listings[3]: set()

listings[3] vs listings[16]
Columns in listings[3] but not listings[16]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[16] but not listings[3]: set()

listings[3] vs listings[17]
Columns in listings[3] but not listings[17]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[17] but not listings[3]: set()

listings[3] vs listings[18]
Columns in listings[3] but not listings[18]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[18] but not listings[3]: set()

listings[3] vs listings[19]
Columns in listings[3] but not listings[19]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[19] but not listings[3]: set()

listings[3] vs listings[20]
Columns in listings[3] but not listings[20]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[20] but not listings[3]: set()

listings[3] vs listings[21]
Columns in listings[3] but not listings[21]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[21] but not listings[3]: set()

listings[3] vs listings[22]
Columns in listings[3] but not listings[22]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[22] but not listings[3]: set()

listings[3] vs listings[23]
Columns in listings[3] but not listings[23]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[23] but not listings[3]: set()

listings[3] vs listings[24]
Columns in listings[3] but not listings[24]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[24] but not listings[3]: set()

listings[3] vs listings[25]
Columns in listings[3] but not listings[25]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[25] but not listings[3]: set()

listings[3] vs listings[26]
Columns in listings[3] but not listings[26]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[26] but not listings[3]: set()

listings[3] vs listings[27]
Columns in listings[3] but not listings[27]: {'BuyerAgencyCompensationType', 'BuyerAgencyCompensation'}
Columns in listings[27] but not listings[3]: set()

listings[3] vs listings[28]
Columns in listings[3] but not listings[28]: {'ListAgentEmail', 'BuyerAgencyCompensation', 'BuyerAgencyCompensationType'}
Columns in listings[28] but not listings[3]: set()

listings[4] vs listings[28]
Columns in listings[4] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[4]: set()

listings[5] vs listings[28]
Columns in listings[5] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[5]: set()

listings[6] vs listings[28]
Columns in listings[6] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[6]: set()

listings[7] vs listings[28]
Columns in listings[7] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[7]: set()

listings[8] vs listings[28]
Columns in listings[8] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[8]: set()

listings[9] vs listings[28]
Columns in listings[9] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[9]: set()

listings[10] vs listings[28]
Columns in listings[10] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[10]: set()

listings[11] vs listings[28]
Columns in listings[11] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[11]: set()

listings[12] vs listings[28]
Columns in listings[12] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[12]: set()

listings[13] vs listings[28]
Columns in listings[13] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[13]: set()

listings[14] vs listings[28]
Columns in listings[14] but not listings[28]: {'ListAgentEmail'}
Columns in listings[28] but not listings[14]: set()


In [110]:
df_list = pd.concat(listings)

print(df_list.shape)

df_list.head()

(897099, 84)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [111]:
df_list.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='str')

In [112]:
duplicate_list = df_list["ListPrice.1"] == df_list["ListPrice"]
print("Duplicate listing price?", duplicate_list.unique())

print()
duplicate_propertytype = df_list["PropertyType"] == df_list["PropertyType.1"]
print("Dubplicate property type?", duplicate_propertytype.unique())

print()
duplicate_closedate = df_list["CloseDate"] == df_list["CloseDate.1"]
print("Dubplicate close date?", duplicate_closedate.unique())

print()
duplicate_living_area = df_list["LivingArea"] == df_list["LivingArea.1"]
print("Duplicate living area?", duplicate_living_area.unique())

print()
duplicate_days_market = df_list["DaysOnMarket"] == df_list["DaysOnMarket.1"]
print("Duplicate days on market?", duplicate_days_market.unique())

print()
duplicate_latitude = df_list["Latitude"] == df_list["Latitude.1"]
print("Duplicate latitude?", duplicate_latitude.unique())

print()
duplicate_longitude = df_list["Longitude"] == df_list["Longitude.1"]
print("Duplicate longitude?", duplicate_longitude.unique())

print()
duplicate_address = df_list["UnparsedAddress"] == df_list["UnparsedAddress.1"]
print("Duplicate address?", duplicate_address.unique())

print()
duplicate_agent_first_name = df_list["ListAgentFirstName"] == df_list["ListAgentFirstName.1"]
print("Duplicate agent first name?", duplicate_agent_first_name.unique())

print()
duplicate_agent_last_name = df_list["ListAgentLastName"] == df_list["ListAgentLastName.1"]
print("Duplicate agent last name?", duplicate_agent_last_name.unique())

print()
duplicate_buyer_office_name = df_list["BuyerOfficeName"] == df_list["BuyerOfficeName.1"]
print("Duplicate buyer office name?", duplicate_buyer_office_name.unique())

Duplicate listing price? [ True False]

Dubplicate property type? [ True]

Dubplicate close date? [False  True]

Duplicate living area? [ True False]

Duplicate days on market? [ True]

Duplicate latitude? [ True False]

Duplicate longitude? [ True False]

Duplicate address? [ True False]

Duplicate agent first name? [ True False]

Duplicate agent last name? [ True False]

Duplicate buyer office name? [False  True]

In [113]:
different_listprice = df_list[df_list["ListPrice.1"] != df_list["ListPrice"]]

different_listprice[["ListingKey", "ListPrice", "ListPrice.1"]]

       ListingKey  ListPrice  ListPrice.1
57     1069730664        NaN          NaN
346    1062101812        NaN          NaN
383    1062034615        NaN          NaN
1088   1060187374        NaN          NaN
2701   1059600517        NaN          NaN
...           ...        ...          ...
33497  1159293218        NaN          NaN
33975  1159256805        NaN          NaN
33982  1159256279        NaN          NaN
33996  1159255951        NaN          NaN
34020  1159254998        NaN          NaN

[2209 rows x 3 columns]

In [114]:
different_closedate = df_list[df_list["CloseDate.1"] != df_list["CloseDate"]]
print("Different CloseDate rows:", different_closedate.shape[0])
print("Value that are different:", different_closedate["CloseDate"].unique())
different_closedate[["ListingKey", "CloseDate", "CloseDate.1"]]

Different CloseDate rows: 637068
Value that are different: <StringArray>
[nan]
Length: 1, dtype: str

       ListingKey CloseDate CloseDate.1
0      1075010398       NaN         NaN
1      1074974457       NaN         NaN
2      1074973329       NaN         NaN
3      1074954552       NaN         NaN
4      1074936537       NaN         NaN
...           ...       ...         ...
36195  1154277796       NaN         NaN
36196  1153629738       NaN         NaN
36198  1151741919       NaN         NaN
36199  1146590110       NaN         NaN
36200  1136798684       NaN         NaN

[637068 rows x 3 columns]

In [115]:
different_latitude = df_list[df_list["Latitude.1"] != df_list["Latitude"]]
print("Different Latitude rows:", different_latitude.shape[0])
print("Value that are different:", different_latitude["Latitude"].unique())
different_latitude[["ListingKey", "Latitude", "Latitude.1"]]

Different Latitude rows: 112569
Value that are different: [nan]

       ListingKey  Latitude  Latitude.1
50     1071104851       NaN         NaN
67     1069615513       NaN         NaN
76     1068189553       NaN         NaN
90     1067816924       NaN         NaN
125    1065257776       NaN         NaN
...           ...       ...         ...
36174  1157413891       NaN         NaN
36175  1157411991       NaN         NaN
36185  1156787991       NaN         NaN
36191  1155792318       NaN         NaN
36197  1153102507       NaN         NaN

[112569 rows x 3 columns]

In [116]:
list_keep_col = [
   # IDs
    "ListingKey",
    "ListingKeyNumeric",
    "ListingId",

    # Dates
    "CloseDate",
    "ListingContractDate",
    "PurchaseContractDate",
    "ContractStatusChangeDate",

    # Price fields
    "ClosePrice",
    "ListPrice",
    "OriginalListPrice",

    # Property characteristics
    "PropertyType",
    "PropertySubType",
    "LivingArea",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "YearBuilt",
    "DaysOnMarket",
    "LotSizeSquareFeet",

    # Location
    "Latitude",
    "Longitude",
    "UnparsedAddress",
    "City",
    "CountyOrParish",
    "PostalCode",
    "StateOrProvince",
    "MLSAreaMajor",

    # School
    "ElementarySchool",
    "ElementarySchoolDistrict",
    "MiddleOrJuniorSchool",
    "MiddleOrJuniorSchoolDistrict",
    "HighSchool",
    "HighSchoolDistrict",

    # Agent / office competitive analysis
    "ListAgentFirstName",
    "ListAgentLastName",
    "ListAgentFullName",
    "ListOfficeName",
    "BuyerAgentFirstName",
    "BuyerAgentLastName",
    "BuyerOfficeName",

    # Useful property features
    "GarageSpaces",
    "ParkingTotal",
    "FireplacesTotal",
    "FireplaceYN",
    "AttachedGarageYN",
    "NewConstructionYN",
    "Levels",
    "Stories",
    "TaxAnnualAmount",
    "TaxYear",

    # Status
    "MlsStatus",
    "BusinessType",

    # Additional property / builder / neighborhood information
    "BuilderName",
    "SubdivisionName"
]

In [117]:
df_list = df_list.drop(
    columns=[
        # Personal/contact info
        "ListAgentEmail",

        # Agent extra information as redundent.
        # Already included agent and office names
        "CoListOfficeName",
        "CoListAgentFirstName",
        "CoListAgentLastName",
        "CoBuyerAgentFirstName",
        "BuyerAgentMlsId",
        "BuyerOfficeAOR",
        "AssociationFeeFrequency",
        "AssociationFee",

        # Extra information of property features
        "AboveGradeFinishedArea",
        "BelowGradeFinishedArea",
        "BuildingAreaTotal",
        "LotSizeAcres",
        "LotSizeDimensions",
        "LotSizeArea",
        "MainLevelBedrooms",
        "StreetNumberNumeric",
        "CoveredSpaces",

        # Duplicate columns of property features
        "PropertyType.1",
        "ListAgentFirstName.1",
        "DaysOnMarket.1",
        "LivingArea.1",
        "Longitude.1",
        "Latitude.1",
        "ListPrice.1",
        "ListAgentLastName.1",
        "CloseDate.1",
        "BuyerOfficeName.1",
        "UnparsedAddress.1"
        ]
    )
df_list.shape

(897099, 55)

In [118]:
df_list = df_list[df_list["PropertyType"] == "Residential"]

print("List of property types:")
print(df_list["PropertyType"].unique())

List of property types:
<StringArray>
['Residential']
Length: 1, dtype: str

In [119]:
print(df_list[df_list.duplicated(keep=False)])
print("Total duplicate rows:", df_list["ListingKey"].duplicated().sum())

Empty DataFrame
Columns: [OriginalListPrice, ListingKey, CloseDate, ClosePrice, ListAgentFirstName, ListAgentLastName, Latitude, Longitude, UnparsedAddress, PropertyType, LivingArea, ListPrice, DaysOnMarket, ListOfficeName, BuyerOfficeName, ListAgentFullName, BuyerAgentFirstName, BuyerAgentLastName, FireplacesTotal, ListingKeyNumeric, MLSAreaMajor, TaxAnnualAmount, CountyOrParish, MlsStatus, ElementarySchool, AttachedGarageYN, ParkingTotal, BuilderName, PropertySubType, SubdivisionName, YearBuilt, BuyerAgencyCompensationType, ListingId, BathroomsTotalInteger, City, BuyerAgencyCompensation, TaxYear, BedroomsTotal, ContractStatusChangeDate, ElementarySchoolDistrict, PurchaseContractDate, ListingContractDate, BusinessType, StateOrProvince, MiddleOrJuniorSchool, FireplaceYN, Stories, HighSchool, Levels, NewConstructionYN, GarageSpaces, HighSchoolDistrict, PostalCode, LotSizeSquareFeet, MiddleOrJuniorSchoolDistrict]
Index: []

[0 rows x 55 columns]
Total duplicate rows: 173

There are 139 duplicate listing key appears more than once, and there are no fully duplicate rows of properties. This suggests that some features are different, such as market status, days on market, list price, close price, or other updated fields in listing data.

In [120]:
df_sold.to_csv("sold_residential.csv", index=False)
df_list.to_csv("listing_residential.csv", index=False)